


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."handle_new_pilot"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.pilot (auth_id, settings)
  values (
    new.id, 
    -- Initialize the JSONB with free tier defaults
    '{
       "is_premium": false,
       "last_played": {
         "board_size_id": null,
         "game_speed_id": null,
         "ai_difficulty_id": null,
         "theme_id": null,
         "volume_id": null
       }
     }'::jsonb
  );
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_pilot"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."achievement" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "icon_path" "text" NOT NULL,
    "reward" integer DEFAULT 100 NOT NULL
);


ALTER TABLE "public"."achievement" OWNER TO "postgres";


ALTER TABLE "public"."achievement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."achievement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."authentication" (
    "id" bigint NOT NULL,
    "authentication_date" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pilot_id" bigint NOT NULL,
    "result_id" bigint NOT NULL
);


ALTER TABLE "public"."authentication" OWNER TO "postgres";


ALTER TABLE "public"."authentication" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."authentication_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."lookup" (
    "id" bigint NOT NULL,
    "lookup_key" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL
);


ALTER TABLE "public"."lookup" OWNER TO "postgres";


ALTER TABLE "public"."lookup" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."lookup_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."match" (
    "id" bigint NOT NULL,
    "start_date" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pilot_id" bigint NOT NULL,
    "board_size_id" bigint NOT NULL,
    "game_speed_id" bigint NOT NULL,
    "theme_id" bigint NOT NULL,
    "ai_difficulty_id" bigint NOT NULL,
    "volume" integer NOT NULL,
    "result_id" bigint NOT NULL,
    "pilot_alien_count" integer,
    "ai_alien_count" integer
);


ALTER TABLE "public"."match" OWNER TO "postgres";


ALTER TABLE "public"."match" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."match_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pilot" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "auth_id" "uuid" NOT NULL,
    "settings" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL
);


ALTER TABLE "public"."pilot" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pilot_achievement" (
    "id" bigint NOT NULL,
    "achievement_id" bigint NOT NULL,
    "pilot_id" bigint NOT NULL
);


ALTER TABLE "public"."pilot_achievement" OWNER TO "postgres";


ALTER TABLE "public"."pilot_achievement" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pilot_achievement_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."pilot" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pilot_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."achievement"
    ADD CONSTRAINT "achievement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."authentication"
    ADD CONSTRAINT "authentication_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lookup"
    ADD CONSTRAINT "lookup_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pilot_achievement"
    ADD CONSTRAINT "pilot_achievement_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pilot"
    ADD CONSTRAINT "pilot_auth_id_key" UNIQUE ("auth_id");



ALTER TABLE ONLY "public"."pilot"
    ADD CONSTRAINT "pilot_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."authentication"
    ADD CONSTRAINT "authentication_pilot_id_fkey" FOREIGN KEY ("pilot_id") REFERENCES "public"."pilot"("id");



ALTER TABLE ONLY "public"."authentication"
    ADD CONSTRAINT "authentication_result_id_fkey" FOREIGN KEY ("result_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_ai_difficulty_id_fkey" FOREIGN KEY ("ai_difficulty_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_board_size_id_fkey" FOREIGN KEY ("board_size_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_game_speed_id_fkey" FOREIGN KEY ("game_speed_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_pilot_id_fkey" FOREIGN KEY ("pilot_id") REFERENCES "public"."pilot"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_result_id_fkey" FOREIGN KEY ("result_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_theme_id_fkey" FOREIGN KEY ("theme_id") REFERENCES "public"."lookup"("id");



ALTER TABLE ONLY "public"."pilot_achievement"
    ADD CONSTRAINT "pilot_achievement_achievement_id_fkey" FOREIGN KEY ("achievement_id") REFERENCES "public"."achievement"("id");



ALTER TABLE ONLY "public"."pilot_achievement"
    ADD CONSTRAINT "pilot_achievement_pilot_id_fkey" FOREIGN KEY ("pilot_id") REFERENCES "public"."pilot"("id");



CREATE POLICY "Allow all operations for now" ON "public"."authentication" USING (true);



CREATE POLICY "Allow all operations for now" ON "public"."match" USING (true);



CREATE POLICY "Allow all operations for now" ON "public"."pilot" USING (true);



CREATE POLICY "Allow all operations for now" ON "public"."pilot_achievement" USING (true);



CREATE POLICY "Allow public read" ON "public"."achievement" FOR SELECT USING (true);



CREATE POLICY "Allow public read" ON "public"."lookup" FOR SELECT USING (true);



ALTER TABLE "public"."achievement" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."authentication" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lookup" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."match" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pilot" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pilot_achievement" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_pilot"() TO "postgres";
GRANT ALL ON FUNCTION "public"."handle_new_pilot"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_pilot"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_pilot"() TO "service_role";



GRANT ALL ON TABLE "public"."achievement" TO "postgres";
GRANT ALL ON TABLE "public"."achievement" TO "anon";
GRANT ALL ON TABLE "public"."achievement" TO "authenticated";
GRANT ALL ON TABLE "public"."achievement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."achievement_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."achievement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."achievement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."achievement_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."authentication" TO "postgres";
GRANT ALL ON TABLE "public"."authentication" TO "anon";
GRANT ALL ON TABLE "public"."authentication" TO "authenticated";
GRANT ALL ON TABLE "public"."authentication" TO "service_role";



GRANT ALL ON SEQUENCE "public"."authentication_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."authentication_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."authentication_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."authentication_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."lookup" TO "postgres";
GRANT ALL ON TABLE "public"."lookup" TO "anon";
GRANT ALL ON TABLE "public"."lookup" TO "authenticated";
GRANT ALL ON TABLE "public"."lookup" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lookup_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."lookup_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."lookup_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lookup_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."match" TO "postgres";
GRANT ALL ON TABLE "public"."match" TO "anon";
GRANT ALL ON TABLE "public"."match" TO "authenticated";
GRANT ALL ON TABLE "public"."match" TO "service_role";



GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pilot" TO "postgres";
GRANT ALL ON TABLE "public"."pilot" TO "anon";
GRANT ALL ON TABLE "public"."pilot" TO "authenticated";
GRANT ALL ON TABLE "public"."pilot" TO "service_role";



GRANT ALL ON TABLE "public"."pilot_achievement" TO "postgres";
GRANT ALL ON TABLE "public"."pilot_achievement" TO "anon";
GRANT ALL ON TABLE "public"."pilot_achievement" TO "authenticated";
GRANT ALL ON TABLE "public"."pilot_achievement" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pilot_achievement_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."pilot_achievement_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pilot_achievement_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pilot_achievement_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pilot_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."pilot_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pilot_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pilot_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







